### ISSUE TITLE
`daily_plot.py` throws uncaught exception (`ValueError`) when there's nothing to plot because the DataFrame is empty

### ISSUE THREAD

**Issue by cgomesu** [mcguirepr89/BirdNET-Pi#726]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**

If the `birds.db` database does not contain any entries for today, then when `chart_viewer.service` calls `daily_plot.py`, the latter throws an uncaught exception (`ValueError`):

```python
 Traceback (most recent call last):
   File "/usr/local/bin/daily_plot.py", line 67, in <module>
     norm = plt.Normalize(confmax.values.min(), confmax.values.max())
   File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/numpy/core/_methods.py", line 43, in _amin
     return umr_minimum(a, axis, None, out, keepdims, initial, where)
 ValueError: zero-size array to reduction operation minimum which has no identity
```

which causes `chart_viewer.service` to enter `FAILURE` state and adds unnecessary entries to syslog (see `python3` entries):

```txt
Feb 04 13:06:38 birdnetpi birdnet_analysis.sh[1000952]: Files loaded
Feb 04 13:06:39 birdnetpi birdnet_analysis.sh[1000952]: RECORDING_LENGTH set to 30
Feb 04 13:06:39 birdnetpi env[1000994]: Line = 2023-02-04-birdnet-13:05:54.wav.csv
Feb 04 13:06:42 birdnetpi systemd[1]: chart_viewer.service: Scheduled restart job, restart counter is at 7954.
Feb 04 13:06:42 birdnetpi systemd[1]: Stopped BirdNET-Pi Chart Viewer Service.
Feb 04 13:06:42 birdnetpi systemd[1]: chart_viewer.service: Consumed 13.718s CPU time.
Feb 04 13:06:42 birdnetpi systemd[1]: Started BirdNET-Pi Chart Viewer Service.
Feb 04 13:06:42 birdnetpi systemd[1]: spectrogram_viewer.service: Scheduled restart job, restart counter is at 106026.
Feb 04 13:06:42 birdnetpi systemd[1]: Stopped BirdNET-Pi Spectrogram Viewer.
Feb 04 13:06:42 birdnetpi systemd[1]: Started BirdNET-Pi Spectrogram Viewer.
Feb 04 13:06:43 birdnetpi systemd[1]: spectrogram_viewer.service: Succeeded.
Feb 04 13:06:52 birdnetpi python3[1001021]: Traceback (most recent call last):
Feb 04 13:06:52 birdnetpi python3[1001021]:   File "/usr/local/bin/daily_plot.py", line 67, in <module>
Feb 04 13:06:52 birdnetpi python3[1001021]:     norm = plt.Normalize(confmax.values.min(), confmax.values.max())
Feb 04 13:06:52 birdnetpi python3[1001021]:   File "/home/pi/BirdNET-Pi/birdnet/lib/python3.9/site-packages/numpy/core/_methods.py", line 43, in _amin
Feb 04 13:06:52 birdnetpi python3[1001021]:     return umr_minimum(a, axis, None, out, keepdims, initial, where)
Feb 04 13:06:52 birdnetpi python3[1001021]: ValueError: zero-size array to reduction operation minimum which has no identity
Feb 04 13:06:53 birdnetpi systemd[1]: spectrogram_viewer.service: Scheduled restart job, restart counter is at 106027.
Feb 04 13:06:53 birdnetpi systemd[1]: Stopped BirdNET-Pi Spectrogram Viewer.
Feb 04 13:06:53 birdnetpi systemd[1]: Started BirdNET-Pi Spectrogram Viewer.
Feb 04 13:06:53 birdnetpi systemd[1]: chart_viewer.service: Main process exited, code=exited, status=1/FAILURE
Feb 04 13:06:53 birdnetpi systemd[1]: chart_viewer.service: Failed with result 'exit-code'.
Feb 04 13:06:53 birdnetpi systemd[1]: chart_viewer.service: Consumed 11.222s CPU time.
Feb 04 13:06:53 birdnetpi systemd[1]: spectrogram_viewer.service: Succeeded.
```

the fix for this issue is straightforward:

- in `daily_plot.py`, one could simply check if the today's df (`df_plt_top10_today`) is empty and stop execution if true. for example, in https://github.com/mcguirepr89/BirdNET-Pi/blob/main/scripts/daily_plot.py#L50, add the following check:

    ```python
    # Quit if there is nothing to plot for today
    if df_plt_top10_today.empty: exit(0)
    ```

**To Reproduce**
1. in `birds.db`, remove any detections from today
2. execute `daily_plot.py`

**Expected behavior**
`daily_plot.py` should handle cases in which there's nothing to plot because this is a fairly common situation.

**Screenshots**
NA

**Additional context**
NA

**Your build**
RPI 3B

**Code or log snippets**
Relevant code and log entries in the bug description

**Comment by ehpersonal38** [comment]
This is great! Thank you so much for your contribution, I'll be adding it to the main repo now 🐤
