### ISSUE TITLE
Model error

### ISSUE THREAD

**Issue by lloydbayley** [mcguirepr89/BirdNET-Pi#900]
The server has stopped and I can't restart it again. It's really weird. Just started happening. Not sure if it was an update or something else.

It's out of my territory when it comes to the model, so here's the output.

```
May  9 22:39:30 birdnetpi python3[14698]: LOADING TF LITE MODEL... Traceback (most recent call last):
May  9 22:39:30 birdnetpi python3[14698]:   File "/usr/local/bin/server.py", line 623, in <module>
May  9 22:39:30 birdnetpi python3[14698]:     start()
May  9 22:39:30 birdnetpi python3[14698]:   File "/usr/local/bin/server.py", line 612, in start
May  9 22:39:30 birdnetpi python3[14698]:     INTERPRETER = loadModel()
May  9 22:39:30 birdnetpi python3[14698]:   File "/usr/local/bin/server.py", line 76, in loadModel
May  9 22:39:30 birdnetpi python3[14698]:     myinterpreter = tflite.Interpreter(model_path=modelpath, num_threads=2)
May  9 22:39:30 birdnetpi python3[14698]:   File "/home/birdpiadmin/BirdNET-Pi/birdnet/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 373, in __init__
May  9 22:39:30 birdnetpi python3[14698]:     _interpreter_wrapper.CreateWrapperFromFile(
May  9 22:39:30 birdnetpi python3[14698]: ValueError: Could not open '/home/birdpiadmin/BirdNET-Pi/model/.tflite'.
May  9 22:39:30 birdnetpi systemd[1]: birdnet_server.service: Main process exited, code=exited, status=1/FAILURE
May  9 22:39:30 birdnetpi systemd[1]: birdnet_server.service: Failed with result 'exit-code'.
May  9 22:39:30 birdnetpi systemd[1]: birdnet_server.service: Consumed 4.907s CPU time.
May  9 22:39:32 birdnetpi systemd[1]: Stopped BirdNET Analysis Server.
May  9 22:39:32 birdnetpi systemd[1]: birdnet_server.service: Consumed 4.907s CPU time.
May  9 22:39:32 birdnetpi systemd[1]: Started BirdNET Analysis Server.
May  9 22:39:36 birdnetpi python3[14758]: LOADING TF LITE MODEL... Traceback (most recent call last):
May  9 22:39:36 birdnetpi python3[14758]:   File "/usr/local/bin/server.py", line 623, in <module>
May  9 22:39:36 birdnetpi python3[14758]:     start()
May  9 22:39:36 birdnetpi python3[14758]:   File "/usr/local/bin/server.py", line 612, in start
May  9 22:39:36 birdnetpi python3[14758]:     INTERPRETER = loadModel()
May  9 22:39:36 birdnetpi python3[14758]:   File "/usr/local/bin/server.py", line 76, in loadModel
May  9 22:39:36 birdnetpi python3[14758]:     myinterpreter = tflite.Interpreter(model_path=modelpath, num_threads=2)
May  9 22:39:36 birdnetpi python3[14758]:   File "/home/birdpiadmin/BirdNET-Pi/birdnet/lib/python3.9/site-packages/tflite_runtime/interpreter.py", line 373, in __init__
May  9 22:39:36 birdnetpi python3[14758]:     _interpreter_wrapper.CreateWrapperFromFile(
May  9 22:39:36 birdnetpi python3[14758]: ValueError: Could not open '/home/birdpiadmin/BirdNET-Pi/model/.tflite'.
May  9 22:39:36 birdnetpi systemd[1]: birdnet_server.service: Main process exited, code=exited, status=1/FAILURE
May  9 22:39:36 birdnetpi systemd[1]: birdnet_server.service: Failed with result 'exit-code'.
May  9 22:39:36 birdnetpi systemd[1]: birdnet_server.service: Consumed 4.936s CPU time.
May  9 22:39:43 birdnetpi systemd[1]: Stopped BirdNET Analysis Server.
```

Rebooting the system clears it at first but then it does it again.
Restarting the server (sudo systemctl status birdnet_server.service or using the restart_services.sh), yields a stuck loop...

No webpage, no fun! No bueno!
Ideas on the back of a postcard please!

**Comment by lloydbayley** [comment]
That was very unwise.
Rebuilds and backups fix everything.
