### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by krummrey** [mcguirepr89/BirdNET-Pi#985]
### PLEASE READ THE DOCUMENTATION BEFORE SUBMITTING AN ISSUE
**Describe the bug**
It seems that the day before yesterday my installation broke. The log repeats this message over and over...

**Code or log snippets**
```
Traceback (most recent call last):
23:50:16---  File "/usr/local/bin/server.py", line 11, in <module>
23:50:16---    import librosa
23:50:16---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
23:50:16---    from . import core
23:50:16---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/core/__init__.py", line 6, in <module>
23:50:16---    from .audio import *  # pylint: disable=wildcard-import
23:50:16---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/librosa/core/audio.py", line 11, in <module>
23:50:16---    import scipy.signal
23:50:16---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/scipy/signal/__init__.py", line 331, in <module>
23:50:16---    from scipy.stats import scoreatpercentile
23:50:16---  File "BirdNET-Pi/birdnet/lib/python3.9/site-packages/scipy/stats/__init__.py", line 494, in <module>
23:50:16---    from ._multivariate import *
23:50:16---  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
23:50:16---  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
23:50:16---  File "<frozen importlib._bootstrap_external>", line 918, in get_code
23:50:16---  File "<frozen importlib._bootstrap_external>", line 587, in _compile_bytecode
23:50:16---ValueError: bad marshal data (unknown type code)
```

**Comment by srd424** [comment]
If I had to hazard a guess I'd say something got corrupted - that error looks to coming from the guts of the python interpreter :(
